### ISSUE TITLE
Library not loaded: /usr/local/opt/portaudio/lib/libportaudio.2.dylib

### ISSUE THREAD

**Issue by rtalwar26** [Streampunk/naudiodon#3]
Am running this in my app 
```javascript
import portAudo from "naudiodon"

console.log(portAudo.getDevices())
```
and get the following error
```
Library not loaded: /usr/local/opt/portaudio/lib/libportaudio.2.dylib
  Referenced from: /Users/<user>/personal/Projects/node/prjname/node_modules/naudiodon/build/Release/naudiodon.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings 
```

**Comment by sparkpunkd** [comment]
Thanks for reporting the issue. I'm travelling at the moment and don't have a Mac to try this on. 

Can you let me know your Mac OS version? Portaudio has been relying on deprecated carbon audio interfaces and they may no longer be supported in the latest version.

I have a plan to fix port audio and contribute it back. I have already done this for another audio API.

**Comment by rtalwar26** [comment]
Mac 10.12.6 (16G29)
Mac node v6.9.1

Thanks

**Comment by sparkpunkd** [comment]
I've fixed the issues I referred to with carbon versions by building my own portaudio library. This is now included in the latest version of node-portaudio. 

However, looking again at your error message, for some reason your system is trying to load the portaudio from the system library path. It should be using the version provided with the project in `portaudio/bin/libportaudio.dylib` which is copied to `build/release/libportaudio.dylib`. The easiest solution would be to install portaudio separately with something like `brew install portaudio`. You could also try `node-gyp rebuild`?

**Comment by mmckegg** [comment]
I am also encountering this on macOS 10.12.6 (16G29)

```
Library not loaded: /usr/local/lib/libportaudio.2.dylib
  Referenced from: /Users/matt/Code/loop-drop-app/node_modules/naudiodon/build/Release/naudiodon.node
  Reason: image not found
```

Running inside of electron 1.6.15

**Comment by sparkpunkd** [comment]
Found a link inside the new locally built portaudio dylib up to a local install of portaudio. Updated with install_name_tool as described here https://blogs.oracle.com/dipol/dynamic-libraries,-rpath,-and-mac-os to use the one provided.

**Comment by mmckegg** [comment]
Hey thanks for that, unfortunately I'm still experiencing an issue:

```
Uncaught Error: dlopen(/Users/matt/Code/loop-drop-app/node_modules/naudiodon/build/Release/naudiodon.node, 1): Library not loaded: libportaudio.dylib
  Referenced from: /Users/matt/Code/loop-drop-app/node_modules/naudiodon/build/Release/naudiodon.node
  Reason: image not found
```

It looks like it is now trying to find the file in the working directory because if I copy "libportaudio.dylib" into the root folder of my project, it works fine.

This is the case in both Node 6.11.3 and Electron 1.6.16.

**Comment by sparkpunkd** [comment]
I'm on a learning curve with dylib references. I've had another go at setting the relative path reference in the binary and checked it in. Let me know if that resolves the issue.

**Comment by mmckegg** [comment]
Okay, that fixed it for me 🎆 

Thanks very much!

**Comment by sparkpunkd** [comment]
Phew - job done and how to do linking on Mac now better understood :-)
